apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::891612549689:user/kubeconfig-client
      username: kubeconfig-client
      groups:
        - system:developers
